[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "be86351c9e8184fa9f7a307cd5f0bc842f1e76ac"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[MPIABI.download]]
    sha256 = "778870bcb350c488606c43bf19ac43e9fa63a1742c54b0c8d6f6badc7b39e8d5"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.aarch64-apple-darwin-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "666208db52c1dd32562d6e6e54009468bdc4a740"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "db292aa422aea7c1e90f39ff2cbc20c7f45db7ce96d0da9cd857504e287ce7b0"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.aarch64-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "3f33b50c61e80a6a9cce1464cae64deb5225d986"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "d3abb2fbb8ce85a142104d43ae1513458bf36e6b2836edfdd24aa0b5314c9d2f"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.aarch64-linux-musl-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "42bce3ee88416527bca09f38e8b0fba38def5d8a"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[MPIABI.download]]
    sha256 = "ae0b37914b1f8782d061b701c8c5e2c00e71e9dfe3f60de598565bf949e1fd8f"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.aarch64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "01fc9c07ffc8fbf3151d8d17eaeb04db3ae4a1d9"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "c29b2068e01120f148627c6f8e0d53754749dec96fb30478864dcc9ed60296ad"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.armv6l-linux-gnueabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b7a794125a284ddc50e7085cb026ae2b7071ba0b"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "c0453124e47c308060db98cddb27f6eb9a3f1e2b4d0a75178e98079c4c55a5fc"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.armv6l-linux-musleabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2db1931962294af2bdb976d562a68fc3e99ee050"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "c1ab434415c8cd4bc153ec621e68b364b7733c3e839de1765d56df0c8a28cfe6"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.armv7l-linux-gnueabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "313fea6ba693dc9303d9df09bd9b602b765ef9c5"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "f0788a7d9de91fe97d9e7cc6d7df2fced0a104837d1a39cfdf9b7e973803ee95"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.armv7l-linux-musleabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "i686"
git-tree-sha1 = "392be237f58981218086290eec2198a4c84ca6a5"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "48a2b2ab884534f152401578fab6d758b9cb6c7d7324373a42fed59429455d57"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.i686-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "i686"
git-tree-sha1 = "f1be62be572d5e759fcd2fa0b966f6e7b018d87c"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "bd347eb34ebde1a681ced74c1d6961e9b5a55d1e836dd7c2c97c7e48b5789bf6"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.i686-linux-musl-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "powerpc64le"
git-tree-sha1 = "45e4bcde4004259ed6606baef098d35a05e7c471"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "46417c6cdc28abb186a7888cdd489214d5653217ce258ecbaf109ae635f2d8db"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.powerpc64le-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "riscv64"
git-tree-sha1 = "1421c73ac0d24b9db4c58fa182a33f4e819c1e44"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "62fc4f053532d37260a2252b342ad93e8dd8643de840dc9a4bc142768d8d15bf"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.riscv64-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "d2e268808eeaecd1bf3c3d658e00747ff4deb1a5"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[MPIABI.download]]
    sha256 = "38caef9bb6dcca5aed87d3f56558b70abff70f37927b934cdfe79c545452512e"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.x86_64-apple-darwin-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "16755bd62bb8a1de1251acb0ad014de694c1e09a"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "bc0d58f1bc8d828b748d9763a9770071703fd58f73b5a024bc5f0ce3f954bf17"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.x86_64-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "b1d1c6931df4907bc28621aee948649cdfe668e4"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "a7b94d48c3580ab3c68dd8ce49d5c25068dd66da44d24f30803cbed48928d3bb"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.x86_64-linux-musl-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "e55e40a69c3d36dc537a3cbec759a4bf9ccf2fab"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[MPIABI.download]]
    sha256 = "7ed693d05ed9797d28d9676fc32a16a9cb1281971f9cc40cc437973f2c39be21"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.3+0/MPIABI.v0.1.3.x86_64-unknown-freebsd-mpi+mpiabi.tar.gz"
