[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "a7c4e27f92381df871b40c5f1a4dff459bea2b2c"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[MPIABI.download]]
    sha256 = "530a5923bcb9128c4275b259603066032e0fb67fdac198a53758879f27ebf510"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.aarch64-apple-darwin-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "16026840c0df54ab28e025eef85300e8c49ec09a"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "a5d403e8a3f2cb7db4f392559e50a5ea27d7aa187fe152f989e18fb677b21963"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.aarch64-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "dcdebccc3405da0aff097e9724d230f5fb0950e7"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "5ee0ad47cfbde10e79da15a8ed634e8c4ff01749977ba712f9c404b15eac5740"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.aarch64-linux-musl-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "6c3e62e32c672b8218f83362484a0f65fb57d891"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[MPIABI.download]]
    sha256 = "693938f0817bff583dc03f2a6330ea9acc32e2a20cb8941151b8a11f4182ec72"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.aarch64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f6762b1cd8a2608f7b830abd1360df3c29a5c576"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "f76bf4de5756ac6c94aaf20d12939c54cfbee5a30848cc154fe7109e411db15f"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.armv6l-linux-gnueabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5ca970ece5bd96a9979185e67a38125c8a50dc71"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "c47eb4171bce8f3a5b9868f6f0e11975aa1ff0e8d99a373e980077d3f82e1912"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.armv6l-linux-musleabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d8ce80189bbe7583f9b4417fbd42fe83a9531e9e"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "feb919977407cf579d7c511b52d66be0ed9312fd1e43f6c6a3163f4a67687c30"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.armv7l-linux-gnueabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9fa190c12568803ef19a4f3370e18d284c5cd01d"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "e7bdc67ceacc10924ebcde8833806d4e9a829b6fabf04b95ec6745d8f00b1e2f"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.armv7l-linux-musleabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "i686"
git-tree-sha1 = "5e6ce4f425c4f89f8e465b7246731ff8c1db9d89"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "010ca8f236254653b000fcbf8042d4358debd0fd7270c4f0c6fe681f1325d600"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.i686-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "i686"
git-tree-sha1 = "1e80727149356276ab6f7ef4ce4b70b2e679f50f"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "cb1a361030c4cfedcdc49d4615f3902dd86fbdc0f62cc93de39fdd56d15ff0f4"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.i686-linux-musl-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "powerpc64le"
git-tree-sha1 = "2ede362f4bc13940a11289d406beff35f4140eee"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "8f79b2754f84b6fc188ed984eed6df9d8647eb5906397efecf054409fe1b1f99"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.powerpc64le-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "riscv64"
git-tree-sha1 = "00298db38d86fd35a369126871524c734cbfc5cd"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "3145cc950a0160afd4c37d1e2246b2bc2a3859a88a573c9a6c5f86c272d766ca"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.riscv64-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "9deb24152a2c70b63e378e77a7fda29d3f6b2336"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[MPIABI.download]]
    sha256 = "82a98db0a70c590e4caa101dcc978d9af7e72ba77b52ce1213129a3663a64e0f"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.x86_64-apple-darwin-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "455a96811e4950a64d618a2e2d49090bca74193c"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "77211156eace64a551543962eba0d8cd7d5ccf76938fc4e1a8d0473e7f29e783"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.x86_64-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "681f9c1d4468a630b8d6a1e9a704dffa73db45f3"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "80f0fd37bfec3581b87d9985e0073fc7bf99c609a830b4f47de2dbcc7f1f8ce7"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.x86_64-linux-musl-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "01efa9c9addbdbb3634ea64cf77fc9808f3d3c8c"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[MPIABI.download]]
    sha256 = "d224c81e526a2c14ef0fa73b68f1ff7f84ae12fcf209c136342ae9b00980ba6f"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v1.0.0+0/MPIABI.v1.0.0.x86_64-unknown-freebsd-mpi+mpiabi.tar.gz"
