[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "51c350ae61ce7aac261ae42a0b9c38239eef552f"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[MPIABI.download]]
    sha256 = "53bb2440167b87d9090360054223288c5d5a170575f31cde9fae02513373dc36"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.aarch64-apple-darwin-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "b6ee03fb7f2d8208fe6012af538fb2a1175d9daa"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "be9a1f5d35bb100e9767b026c78deb15fa7efd6042b847c597a54d6ad9a2508f"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.aarch64-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "9545eac6a1c7a825d603c0d8f85cc79bd62e47cb"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "093f40eff245b1adce36dc4ba758e48b9e7e3c43dd9d624ff77bdc33e540d733"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.aarch64-linux-musl-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "aarch64"
git-tree-sha1 = "0417b28b875e7bd7776d4358bb73ef0d4dea04bf"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[MPIABI.download]]
    sha256 = "0c20eb98a18746bd32080fc5bd16bbe6187b40757f1ff3984d9bfaee25d34a80"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.aarch64-unknown-freebsd-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5ff5b5ca4068474aa8898b3f3649d9bd96e2c129"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "250092ccbad2f473f85f2ecb076713891fe39796405052a212087d3edb9550d9"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.armv6l-linux-gnueabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2f6be33a85c700812ed3022fde65f26afb4b2e7b"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "85c96178e416befd2b3ff729498def4b288d2d715c6e04e3e57885ccc589a2f9"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.armv6l-linux-musleabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "92e1efb680dab67bf13b1230a5faabed66fed4ae"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "c577d2d62e568123fa30bf9457419a00c8b52b9752dcd47bd7a18be5b76350f0"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.armv7l-linux-gnueabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "95addefca3a0f60ec1d4df88a3b6172a547df4aa"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "5419dea5d7ae3a5922493175484df595b1fd28e25bafe1bfaa2e415c7c49ff91"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.armv7l-linux-musleabihf-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "i686"
git-tree-sha1 = "4beb62d2e64ead86e8400057ead48100f389a421"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "b55782fe572d5196867cc72438ff0515be3f7aa548fa5490024f2fab36f300e9"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.i686-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "i686"
git-tree-sha1 = "3ff2d09f9adfa4fcc6ce68e6ca08ff532d04c6ca"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "e9366c2ff46e3a308a46564b19680e5344c556933fc0c28725e6a73db24a734d"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.i686-linux-musl-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "powerpc64le"
git-tree-sha1 = "d98b1747ec309e3fc774ba6184aaeab792c4e7b4"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "9e768c2ae4426e15fe1464a65aa1976d6ec2b19d4f91433fca3a79e1ab3c4f01"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.powerpc64le-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "riscv64"
git-tree-sha1 = "ec4e2005196d942ce8b5fb82b173eb11a0aac781"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "45f2548f8f3c6624e8c32331625983c8760d1409734b69e4ab1d4ac96e81f212"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.riscv64-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "eafad6141c748b3e85a701d19564fbc62aca1c3f"
lazy = true
mpi = "mpiabi"
os = "macos"

    [[MPIABI.download]]
    sha256 = "bc7e308c1757481a146ff9f15912b20c01d5618b123989bc0ce338b039e5aa40"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.x86_64-apple-darwin-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "f6b75f2d5b004bf9d44aebf5663cfff86011a07c"
lazy = true
libc = "glibc"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "91cc1bb8f76fe974f5981189f9b9ee977b19b1c58aeda109b5fbde2f8a86300e"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.x86_64-linux-gnu-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "a29cb9efa7c992436043902a1a67d2f45bfb3874"
lazy = true
libc = "musl"
mpi = "mpiabi"
os = "linux"

    [[MPIABI.download]]
    sha256 = "86359892522ae4277c640bd97e6bfd5bebae70ef554f632d9a761b28336c97d8"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.x86_64-linux-musl-mpi+mpiabi.tar.gz"
[[MPIABI]]
arch = "x86_64"
git-tree-sha1 = "887ccfa3ae0da41a1c025456f66fea0e6b6e8950"
lazy = true
mpi = "mpiabi"
os = "freebsd"

    [[MPIABI.download]]
    sha256 = "e1794dbe433bd8d7926a7a329ccab4c41dd89c00778152f7ea2d28878160e140"
    url = "https://github.com/JuliaBinaryWrappers/MPIABI_jll.jl/releases/download/MPIABI-v0.1.2+0/MPIABI.v0.1.2.x86_64-unknown-freebsd-mpi+mpiabi.tar.gz"
