# Autogenerated wrapper script for MPIABI_jll for aarch64-apple-darwin-mpi+mpiabi
export libmpi, mpiexec

using CompilerSupportLibraries_jll
using Hwloc_jll
JLLWrappers.@generate_wrapper_header("MPIABI")
JLLWrappers.@declare_library_product(libmpi, "@rpath/libmpi_abi.0.dylib")
JLLWrappers.@declare_executable_product(mpiexec)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Hwloc_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libmpi,
        "lib/libmpi_abi.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_executable_product(
        mpiexec,
        "bin/mpiexec",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
